### ISSUE TITLE
Merge E4111 scripts into a new script called "REVW PAY PLAN"

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#468] opened 2016-08-26 19:35 UTC
This was discussed at yesterday's event. @levesswe has volunteered because she's awesome.

The two scripts I have:
- E4111 SUSP SCRUBBER
- E4111 WORKLIST SCRUBBER

@levesswe, I'm open to other names for it as well, just let me know.

**Comment by theVKC** [comment] 2016-09-12 20:28
@levesswe, can I get an update on this one? It's tied to the initial release, I might remove it and we can tie it for the followup.

**Comment by theVKC** [comment] 2016-09-13 17:18
@levesswe isn't sure she can get to this shortly. I'm going to plan on taking it so it can be done prior to release. #FewerButtonsMeansHappierChildSupportPeople

**Comment by theVKC** [comment] 2016-09-23 15:21
I am removing this from the milestone and initial release project, because I don't believe I can prioritize it over some bugs and enhancements that will add value before the initial release.

If anyone wants it, let me know. If nobody takes it by October 3rd, I'm going to plan on closing it.

**Comment by heatherallen** [comment] 2016-11-14 20:35
@theVKC I"ll take this on

**Comment by heatherallen** [comment] 2016-11-16 16:39
@MN-Script-Team/prism-scriptwriters looking for some feedback and help on this.  I"m planning on merging these 2 scripts.  I see the instructions for the E4111 WORKLIST SCRUBBER script that appears to make an excel spreadsheet along with purging the worklist on cases where the DL is already suspended.  My question is what does the E4111 SUSP SCRUBBER script do or was intended to do?  Just trying to figure out what is needed in the merging of the 2.  Thanks!

**Comment by theVKC** [comment] 2016-11-16 16:40
I believe @levesswe created this script but I'm not sure.

**Comment by levesswe** [comment] 2016-11-17 16:02
I created both versions of the scripts - and their names, which have confused others ever since!  Sorry about that!  E4111 SUSP Scrubber is now called review-pay-plan---dl-is-suspended, and as you pointed out, removes the E4111 worklists on cases that already have DL suspended.  E4111 WORKLIST SCRUBBER is now called review-pay-plan---recent-activity.  It's purpose is to display recent payment and obligation information one at a time in a loop and allow the user to determine whether the E4111 worklist should be purged.  I have wanted for a LONG LONG time to have the recent activity script modified to use the same kind of logic to produce the excel spreadsheet that the DL suspension one uses, as it is less buggy (the current version seems to skip some).  If we do that, the idea is that we could include the DL suspension functionality into the recent activity script for better efficiency.

**Comment by heatherallen** [comment] 2016-11-17 21:22
Thanks @levesswe! I think I get the difference of each script, so if I'm hearing you correctly we are wanting to keep the DL suspended one as is but modify the Recent Activity one to use Excel?  Also, thoughts on enhancing the DL Suspended one to include OLS?

**Comment by levesswe** [comment] 2016-11-18 16:54
Our goal is to integrate the DL suspended functionality to recent activity script, too, so that when all is done it could be just one script.  I would take things one step at a time and prioritize the fixes first - but yes, we could add OLS functionality, too!

**Comment by theVKC** [comment] 2016-11-28 19:42
Can I get an update on where you might be with this one, @heatherallen?

**Comment by heatherallen** [comment] 2016-11-28 20:51
I have not had a chance to work on this since the last hackathon....I would hope to set aside part of a day this week or next to work on it and I can give you a better idea of how much longer I would need.

**Comment by theVKC** [comment] 2016-11-28 20:51
Good deal, thanks for the update @heatherallen!

**Comment by heatherallen** [comment] 2017-01-18 17:29
@theVKC. I have merged the 2 scripts and have a draft, BUT I would like to test this script on my own when I get this worklist at the beginning of next month to make sure it is working the way I anticipate it to do so.  Once I test and ensure it is working properly I'll create pull request and have others test.

**Comment by heatherallen** [comment] 2017-04-12 21:07
@MN-Script-Team/prism-scriptwriters.  Anyone out there that would be able to help me with this script?  Where I'm running into an issue is if the script is not purging the E4111 worklist how to I get the script to read and process the next E4111 worklist and case?  Any help is appreciated. :)

**Comment by heatherallen** [comment] 2017-04-21 17:07
I think I have successfully combined the 2 bulk scripts and created the suggested RVW Pay Plan script.  Could I get a few people to test this, especially if anyone gets the E4111 worklist and the DL is already suspended; as I want to make sure it is purging the worklist?   I have designed the script to go thru all cases that have the E4111 worklist-"RVW DLS Pay Plan NCP Delinquent" and display in an Excel Spreadsheet, if the NCPs DL is suspended, if the worklist was purged, when the last payment received was and in what amount.  

I have provided a link to the code if some people could test this out for me, that would be greatly appreciated. :) @levesswe, @KallistaImdieke, @jlmartinone, @gretchent74  (please share with any others you know may be able to test)
https://gist.github.com/heatherallen/eefdeb54997599f2916a7ff6497e0ae6

Thanks for your help!!

**Closed** 2018-02-27 16:24 UTC
Labels: Sleeper, new script idea
