### ISSUE TITLE
Issues with Windows 10 Build and Defender Anti-Virus 1703+ (1703, 1709)

### ISSUE THREAD

**Issue by WCMattAnderson** [MN-Script-Team/DHS-PRISM-Scripts#797] opened 2017-05-24 22:47 UTC
Scripts do not come to front of screen when running this build of Windows. Dialog boxes are present in task manager however cannot be seen. - Needed to revert user back to Win10 build 1607.

Tested on Surface Pro 3, Surface Book, Dell E6540 running this build.

**Comment by theVKC** [comment] 2017-07-18 14:57
Hi Matt! Just getting back from leave. Any idea why this might be taking place? I presume this is related to the Surface? I don't know of other agencies using Win10 Anniversary (I do know it's working as expected on Win10 as of last year).

**Comment by WCMattAnderson** [comment] 2017-08-08 15:57
Hi Veronica, I have sent you an email with a video of what it does on Win10 build 1703. It works on Prior builds.

**Comment by WCMattAnderson** [comment] 2017-08-15 23:05
This is my event log error:
Faulting application name: Bzsh.Exe, version: 5.1.0.1230, time stamp: 0x4a8d0977
Faulting module name: OLEAUT32.dll, version: 10.0.15063.332, time stamp: 0x24e598c7
Exception code: 0xc00000fd
Fault offset: 0x0001edcf
Faulting process id: 0x2720
Faulting application start time: 0x01d3161a8b96354f
Faulting application path: C:\Users\<user>\Documents\BlueZone\Bzsh.Exe
Faulting module path: C:\WINDOWS\System32\OLEAUT32.dll

Fault bucket 109017925688, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Bzsh.Exe
P2: 5.1.0.1230
P3: 4a8d0977
P4: COMCTL32.dll
P5: 6.10.15063.0
P6: 7371269e
P7: c0000005
P8: 0005e81c
P9: 
P10: 
Report Id: 6c262df6-1900-4190-9013-bb49871ae98c
Faulting package full name: 
Faulting package-relative application ID: 

@theVKC What version are you running? This is from BlueZone 5.1C2 Build 1325 - If this is old... where can we get new installer files?

**Comment by RoberT-1000** [comment] 2017-08-31 01:22
I am going to upgrade a test computer to Windows 10 build 1703 and will do some testing on BlueZone builds 5.1.2 and 6.1.8.

**Comment by RoberT-1000** [comment] 2017-09-01 20:20
OK...feedback...

The problem seems to be with the way the scripts are written. It looks like we need to create a host object and then interact through the object methods. Please see attached examples. 

@WCMattAnderson , if you are able to test with a 1703 machine, script1703ok.txt (run as vbs) will throw the MsgBox, but script1703notok.txt (run as vbs) throws an exception access violation.

[script1703ok.txt](https://github.com/MN-Script-Team/DHS-PRISM-Scripts/files/1271401/script1703ok.txt)
[script1703notok.txt](https://github.com/MN-Script-Team/DHS-PRISM-Scripts/files/1271402/script1703notok.txt)

**Comment by WCMattAnderson** [comment] 2017-09-02 01:16
This does seem to be the issue. Here is some more information from the rocket site on objects.

https://www3.rocketsoftware.com/bluezone/help/v71/en/bzsh/bzaa_aref_bz-object-methods.htm

**Comment by RoberT-1000** [comment] 2017-09-05 13:13
@WCMattAnderson I'm wondering if this problem is also related to this issue...

https://stackoverflow.com/questions/45274885/vbscript-consumes-memory-after-creators-update-win-10-64bit

**Comment by RoberT-1000** [comment] 2017-09-29 13:31
@WCMattAnderson -- follow-up item. Are you able to get the java version from the user's computer that was experiencing the issue? @IlseFerris and I have been testing. I am having the same problem you reported, and I am running build 1.6.something (really specific, I know) and it seems like v.8, update 121, Build 1.8.0_121-b13 may be working.

**Comment by IlseFerris** [comment] 2017-09-29 13:35
This information was released yesterday from DHS:

MN.IT has confirmed that Java 9 is NOT compatible with MEC². Please DO NOT update to Java 9 until further notice. Desktops will not automatically update or be prompted to update to Java 9.

The current version of Java 8 – Version 8 update 144(1.8.0_144) is compatible with MEC² and users can update to that version if necessary. Oracle will continue to support Java 8 and new versions will be released until September 2018. Please do not update to any new releases until MN.IT has a chance to confirm they are compatible with MEC².

If you have any questions please have your IT staff contact the MAXIS/MEC² System Pager at 651-649-6479

**Comment by WCMattAnderson** [comment] 2017-09-29 13:42
We did have issues a few months back with the new Java updates and MEC2 it was listed as an issue on SIR and they released the issue and must of updated something on their end. We are currently running Java 8 144 on these systems.

**Comment by JakeSherburneCounty** [comment] 2017-10-02 18:59
Hello Everyone,

Regarding the BlueZone Scripts:

We are also having this issue with the Scripts in BlueZone. We're beginning to deploy Windows 10 and have a few test users out there. This is one of the first issues that has popped up.
Looking at the event log we get a similar error to that of what WCMattAnderson has posted. Sometimes we also get a faulting module of dbgcore.dll on bzsh.exe as well.

We have tried several variations of compatibility mode but none have worked thus far.
If anyone has any other ideas please let us know.

**Comment by WCMattAnderson** [comment] 2017-10-02 19:12
Right now we are forced to run 1607 or older for builds on Win10 Pro to work correctly on Win10. 1703 isn't compatible and the falls creator release we are soon to test in the next week or so for compatibility.

**Comment by SCJakePrimus** [comment] 2017-10-04 18:23
Something to note is that if I have Windows 10 1703 running, these scripts appear to work fine if we have windows defender disabled. We are trying to create path and process exclusions for windows defender, but no matter what we try, we cannot get the scripts to work with Windows Defender turned on. This is something we'll continue working on because we would like to be able to be on the latest version of Windows 10.
If anyone has any other ideas on why Windows Defender would be the culprit, and how to fix it, please let us know.

**Comment by WCMattAnderson** [comment] 2017-10-04 19:14
Testing with Defender off here we continue to see the same issue on 1703 build. We have tested with Symantec installed initally and ran into the same problems. Note that some of the buttons will work, but some of them will lock up BlueZone and leave a BlueZone Script Host hidden in the background.

**Comment by theVKC** [comment] 2017-11-20 16:48
OK folks, quick update.

I've spent the last couple of weeks testing assorted workarounds. Currently the only workaround that consistently works is disabling virus protection on Windows Defender. My belief - based on evidence counties have sent me, as well as my own testing - is that the new hypervisor system built into 1703+ isolates BZSH.exe and BZMD.exe from the OLE objects required for most of the BlueZone Scripts functions. 

Rewriting most functions to work around this, accessing OLE using the standard COM objects well supported in Windows, is a trivial work. However, one specific area remains broken even after rewriting functions, and that's the dialog boxes used by the scripts. I believe the Windows API is blocking them still.

I have a plan to build a new system for displaying these dialogs, but it requires additional testing before I'll have a timetable. In the meantime, I advise Windows 10 users to disable virus protection (ideally you have access to a third party solution in this case), or regress back to an earlier build.

I am working as quick as I can on finding a solution: this is my highest priority at the moment.

**Comment by WCMattAnderson** [comment] 2018-01-30 01:55
Seems updating to BlueZone 7.1.5 fixes this for now. Will do some more testing and report tomorrow but scripts seem to be working running build 1709.

**Comment by SCJakePrimus** [comment] 2018-01-30 14:23
@WCMattAnderson Where did you get this new version of BlueZone? When I've talked to MNIT the latest version they were able to send me a link to a 6.1.8 and they still recommended the download site for 5.1.

**Comment by WCMattAnderson** [comment] 2018-01-30 14:36
Sent you the contact details using first.last email format with your name above. He did mention no other Counties have asked for updates recently.

**Comment by SCJakePrimus** [comment] 2018-01-30 17:09
Thank you Matt, we were able to get the new version from them. An initial test did show this was working in Windows 10 with the scripts. We have several users with Windows 10 that need scripts and we will be testing with them as well.

**Closed** 2018-02-27 17:02 UTC
Labels: bug
