### ISSUE TITLE
Arrears Mgmt Review

### ISSUE THREAD

**Issue by KallistaImdieke** [MN-Script-Team/DHS-PRISM-Scripts#560] opened 2016-09-29 21:29 UTC
When trying to run this script we are receiving the issue where it jumps up and starts writing on the case number, name ect as shown in the snap show and we have made sure that there are no characters/symbols  being used in the scripts.

**Comment by theVKC** [comment] 2016-09-30 14:00
!!!

PLEASE DO NOT SHARE SYSTEM SCREENSHOTS, ESPECIALLY WITH CLIENT DATA

**Comment by theVKC** [comment] 2016-09-30 14:02
I removed the system screenshot here, in the future, please email them to me directly.

**Comment by theVKC** [comment] 2016-09-30 14:02
In any case, check to see that the script has an EMSetCursor on the appropriate line before it starts writing CAAD note details.

**Comment by KallistaImdieke** [comment] 2016-09-30 14:12
It is at the start of the script and the script does start out right but after it writes the first screen of the CAAD note and needs to page down it appears that may be when the bug is being caused and it doesn’t page down like it is supposed to and then go to the correct line from there.

**Comment by theVKC** [comment] 2016-09-30 14:15
Check out the script file itself, does it use `write_variable_in_CAAD` and `write_bullet_and_variable_in_CAAD`? Those functions handle the pagination.

**Comment by KallistaImdieke** [comment] 2016-09-30 14:19
I checked the script and yes it does use write_variable_in_CAAD and write_bullet_and_variable_in_CAAD and has    EMSetCursor at the beginning of writing the caad note

**Comment by theVKC** [comment] 2016-09-30 14:20
Well then, it's either

A. A functional problem with the pagination, or
B. A particular string which is causing an issue in the function

You should also ensure it's happening on multiple users across multiple cases.

**Comment by KallistaImdieke** [comment] 2016-09-30 14:22
I did test it on my case also after I was told about the issue but on the same case I will go ahead and see if we can have other cases tested.

Thanks!

**Comment by levesswe** [comment] 2016-09-30 14:23
Yes, it does use those functions.  Also, I wanted to add that this error is reproducible. We have experienced it too.  We were hoping the updated functions library (See Bug #349) would resolve this issue… Apparently not?

Wendy LeVesseur
Child Support Officer

Anoka County Government Center
2100 3rd Avenue, Suite 401
Anoka, MN 55303
763-422-7323

**Comment by theVKC** [comment] 2016-09-30 14:27
It seems odd that it's limited to this particular script, though. And yes, that function may address this, but I've been focusing on prioritizing script organization and planning/prep over functional modifications (I don't have a lot of help on the PRISM functions side at this time, either).

@levesswe, how long has the error been persisting? We should have had an error report as soon as it was first found to be reproducible.

**Comment by theVKC** [comment] 2016-09-30 14:28
(#349 didn't reference any bugs, just an enhancement idea)

**Comment by levesswe** [comment] 2016-09-30 14:38
It’s been a problem at least until June, because that’s when I opened bug #349.  I don’t think it is a problem specifically with this script; I think it is a more global issue related to the functions.  You can ask people and they will tell you they have at times had this same issue with the client contact script and other note scripts.

Personally, I think the volume of data being written is a component of this issue, and with this script in particular, it writes a lot of data.  It might be a good idea to incorporate a “continued from previous note” type of functionality that MAXIS uses (side note: there is a CAAD code for continuing a previous note, M3906), or error handling if the data is too large for the note to handle.



Wendy LeVesseur
Child Support Officer

Anoka County Government Center
2100 3rd Avenue, Suite 401
Anoka, MN 55303
763-422-7323

**Comment by theVKC** [comment] 2016-09-30 14:47
![image](https://cloud.githubusercontent.com/assets/5701751/18995537/3be1e294-86f2-11e6-9d68-476fefe32552.png)

Nothing about your issue in #349 references a problem, though. In the future, if you are indicating a _problem_ with a script or function, you need to say so. The tag (or phrase) _enhancement_ implies  *things are currently working fine but this could be better*. Had this been tagged as a _bug_ or a _problem_, with specific indicators such as the actual script involved, it would have become a priority. It is important to be clear and detailed when leaving issues on GitHub. Please keep that in mind when adding issues.

In any case, I will be modifying the FuncLib issue (https://github.com/MN-Script-Team/BZS-FuncLib/issues/277) to indicate that this is currently causing bugs, and that will move it up on the priorities list.

Marking this as a duplicate (#349), and closing. Work continues on FuncLib.

**Closed** 2016-09-30 14:48 UTC
Labels: duplicate, problem/bug, question
