### ISSUE TITLE
E0002 - Transfers all No Pay worklists into a Spreadsheet & purges the worklist

### ISSUE THREAD

**Issue by KallistaImdieke** [MN-Script-Team/DHS-PRISM-Scripts#720] opened 2017-02-01 18:04 UTC
In Stearns County (since we are case banking) we wanted/needed a script that will review all the E0002 (no pay) work lists on a caseload, and pull them into a spreadsheet along with the work lists date, case number, NCP's name, file location (we use this for Zero order, Incarcerated ect), the date of the last NCP phone contact  and the NCP's phone number & a place to make comments when reviewing the case.

This way we can work of the spread sheet as we may have multiple people working on them at a time, Plus the supervisors are able to spot check to make sure everything was completed correctly and we can sort the cases on the spreadsheet.  

I was wondering if there would be a demand for this with other counties.  I have it drafted and have tested it in the training region but we will be testing it on live cases next week. After I have tested this I can add it to GitHub to be pulled in if there is a demand. 

Thanks!

**Comment by theVKC** [comment] 2017-02-02 02:32
I think that we should bring it onboard. It doesn't have any policy concerns and I could see it being quite helpful. :)

**Comment by KallistaImdieke** [comment] 2017-02-02 14:15
sounds good after I test it on live cases on Monday I will get it uploaded so it can be pulled in as long as there are no changes :-)

**Comment by KallistaImdieke** [comment] 2017-09-27 19:48
The link where the spreadsheet is saved in this script is Stearns County specific and needs to be changed to grab from the global variables thanks!

**Comment by theVKC** [comment] 2017-11-20 16:38
I'm going to take a look at fixing that link as soon as I can.

**Comment by theVKC** [comment] 2018-02-27 16:47
Duplicate of #691. Closing. Will be converted to Python before released.

**Closed by theVKC** 2018-02-27 16:47 UTC
Labels: duplicate, new script idea
