### ISSUE TITLE
Bulk: Review QW Info Bug

### ISSUE THREAD

**Issue by heatherallen** [MN-Script-Team/DHS-PRISM-Scripts#693] opened 2017-01-12 14:46 UTC
Is anyone having issues with this script?  After reviewing the instructions and using the script here in Scott County, it doesn't appear it is doing all it is supposed to be doing as listed in the instructions.  It does not prompt you to enter your worker ID and when the script is running it is not creating the excel spreadsheet.  One of my coworkers ran the script and it did not purge any of her worklists, so we had another person try it and when they ran it the script purged all but one of the worklists but did not create the spreadsheet.

**Comment by paschell** [comment] 2017-01-12 15:47
@heatherallen - I had a coworker comment on Tuesday that the script was not creating the spreadsheet.  I am unable to test as I have no L2500 or L2501 worklists.  I used it last month and it worked as it was intended.   I will try and find a few workers today to test.

**Comment by heatherallen** [comment] 2017-01-12 16:15
@levesswe we did look for the Excel spreadsheet on the taskbar and if it may have been hiding behind some things but we did not see that either :(

**Comment by levesswe** [comment] 2017-01-12 16:36
If the first user did not see any dialogs very likely the script didn't run.  You can have the user try clicking "stop script" and then try again, or try rebooting the computer.  On the computer where it did run, hoover the mouse over the excel icon on the task bar.  It should show two files are open named "Book2" or "Book3" or whatever.  You can then select one and maximize by clicking the square.  See attached image.  Hope that helps!


![icon](https://cloud.githubusercontent.com/assets/11066272/21898552/c8e13142-d8b2-11e6-81a2-5fd1a95f68ff.png)

**Comment by theVKC** [comment] 2017-01-13 15:43
Reading this, I think @levesswe is right on. @heatherallen, can you check again and confirm? If so, we'll close the issue.

**Comment by heatherallen** [comment] 2017-01-19 20:39
I just ran this script again and no Excel Spreadsheet is populating.  It is reviewing and processing the worklists but I am not getting the Excel Spreadsheet.

**Comment by theVKC** [comment] 2017-01-19 20:50
Hmmmm. I wonder if there's something blocking up the muck-works here. As in: is it possible your Excel is running something else and not showing it to you?

**Comment by heatherallen** [comment] 2017-01-19 20:52
Excel was not open when I ran the script....when I get those worklists again should I try with Excel open?

**Comment by levesswe** [comment] 2017-01-20 14:53
My experience has been that having Excel open when running the script does not make the Excel title bar appear maximized.  You would still need to go to the task bar, hoover by Excel, and select a page to make the title bar visible, and then click the box button to maximize.  

Maybe this is something that could be more clearly demonstrated at a hackathon...

**Comment by heatherallen** [comment] 2017-01-20 15:17
Yes maybe this should be demonstrated.  I do not have my Excel pinned to my taskbar, nor is it populated.  In your screen shot it looks like you may have a newer version of Excel, could that be a weird thing to do with it?

**Comment by theVKC** [comment] 2017-01-31 16:13
I'm going to close this for now. If the issue persists, perhaps @levesswe could create a new issue to ensure that the doc is visible? I think there's an OLE object you can use for that.

**Closed by theVKC** 2017-01-31 16:13 UTC
Labels: bug, feedback needed

**Comment by heatherallen** [comment] 2017-02-02 21:18
@theVKC I just was able to try this and works great!!! I like the updates @levesswe

**Comment by levesswe** [comment] 2017-02-02 21:23
Great! :)
