### ISSUE TITLE
BULK - Review Pay Plan Recent Payment Activity

### ISSUE THREAD

**Issue by levesswe** [MN-Script-Team/DHS-PRISM-Scripts#261] opened 2016-03-30 19:46 UTC
Reported bug: isn't removing all matches.

**Comment by theVKC** [comment] 2016-08-01 15:54
@levesswe, do we have an update on this one? I don't see a pull request for it: if it's critical we should attempt to resolve it ASAP.

**Comment by levesswe** [comment] 2016-08-03 20:30
Hi, I am still in the process of fixing this one.  I am close to finishing it but @paschell kept finding bugs...

**Comment by paschell** [comment] 2016-08-03 20:50
Sorry @levesswe .  I have a proposal on the table with management in Anoka to come at the Driver's License Payment Plan Review worklists (E4110 and E4111)  from a  different angle.   I did research on the whole process including input from several other counties and drafted a written proposal.  Although this script has some merit it only does some of what is necessary to complete the process of reviewing a case for compliance on this enforcement remedy.  More will come on this one......

**Comment by theVKC** [comment] 2016-08-03 21:05
@paschell, can you send your proposal to me? I can bring it to my people here as well. That felt good to say.

**Comment by theVKC** [comment] 2016-08-03 21:06
Since this is marked as critical, I am thinking we should terminate access until it's bug-free. Any objections?

**Comment by paschell** [comment] 2016-08-03 21:39
OK and  it is a good thing to have people!!

**Comment by theVKC** [comment] 2016-08-17 16:09
OK, I've been going over the proposal.

@levesswe and any other @MN-CS-Script-Team/prism-scriptwriters or @MN-CS-Script-Team/prism-supervisors... do you think this script should be removed for now, then replaced with a more comprehensive worklist processor? @paschell's proposal looks sound from where I sit, and we can certainly address it at a collaborative meeting or hackathon.

Please let me know if you are in favor of removing it or keeping it on. The winning vote by Monday's hackathon will be acted upon.

**Comment by wrightcountykaren** [comment] 2016-08-17 16:31
I thought this was the kind of thing we were planning to discuss at the hackathon?

Karen Popken
Wright County Child Support Supervisor
Phone: 763-682-7403
How did I do today? Click here to complete our customer service survey.<https://www.surveymonkey.com/r/WCHHS_CSS>

**Comment by theVKC** [comment] 2016-08-17 16:34
@wrightcountykaren we certainly are. But it was indicated to me (I believe by @levesswe) that this issue is considered "critical". So, I didn't want to wait. If folks don't think it's critical I am all for tabling it until the 25th. I didn't want totally broken or policy-incorrect scripts out there. :/

**Comment by levesswe** [comment] 2016-08-17 17:07
I think it’s fine to just discuss it at hackathon.

Wendy LeVesseur
Child Support Officer

Anoka County Government Center
2100 3rd Avenue, Suite 401
Anoka, MN 55303
763-422-7323

**Comment by theVKC** [comment] 2016-08-17 17:20
Good deal. I've removed the "critical" label and we can discuss at Hackathon on Monday.

**Comment by theVKC** [comment] 2016-08-25 18:46
@levesswe believes she can get this done in the next couple of weeks. Go Wendy!

**Comment by theVKC** [comment] 2016-09-12 20:22
@levesswe, can you give me an update on this one?

**Comment by theVKC** [comment] 2016-09-13 17:08
As this is a bug, I'm going to take it to expedite it. I suspect it's a logical loop with when the script drops down to the next line. @KallistaImdieke, @jlmartinone, or @khiestand, can either of you confirm that the problem is that logical loop? If someone can confirm I'll happily build the fix sometime this week.

**Comment by theVKC** [comment] 2016-11-28 17:41
I did not receive any evidence of the problem here. I'm going to close for now since we aren't sure it's a bug.

**Closed by theVKC** 2016-11-28 17:41 UTC
Labels: bug
